version: '3.8'

services:
  rag-api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - app/.env
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./.env:/app/.env:ro
      - ./onnx:/app/onnx:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
